name: Use the Composite Action with Actions

on: 
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu_latest
        steps:
            - uses: actions/checkout@v2
            - name: Do anything else
              run: echo "Pretend to do other things"
              
            #Uses the Composite Action
            - name: Build and Push the Image
              uses: Khushi-Singhania/CompositeActions/.github/workflows/actions.yml@main
              with:
                  registry_username: ${{secrets.REGISTRY_USERNAME}}
                  registry_password: ${{secrets.REGISTRY_PASSWORD}}
                  image_name: my-awesome-app
                  tag: $GITHUB_RUN_NUMBER
