name: My Starter Workflow 1

on:
    workflow_dispatch:
        
jobs:
    call-workflow-in-local-repo:
        uses: ./.github/workflows/reusable-workflow1.yml
    
    print-deploy-result:
        needs: call-workflow-in-local-repo
        runs-on: ubuntu-latest
        steps:
            - name: Print deployment result
              run: echo "${{ needs.call-workflow-in-local-repo.outputs.result}}"
